apiVersion: v1
name: ack-elasticsearchservice-controller
description: A Helm chart for the ACK service controller for elasticsearchservice
version: v0.0.1
appVersion: v0.0.1
home: https://github.com/aws-controllers-k8s/elasticsearchservice-controller
icon: https://raw.githubusercontent.com/aws/eks-charts/master/docs/logo/aws.png
sources:
  - https://github.com/aws-controllers-k8s/elasticsearchservice-controller
maintainers:
  - name: ACK Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/ack-admin
  - name: elasticsearchservice Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/elasticsearchservice-maintainer
keywords:
  - aws
  - kubernetes
  - elasticsearchservice
